services:
  - type: web
    name: restaurant-app
    env: python
    buildCommand: cd server && pip install -r requirements.txt
    startCommand: cd server && gunicorn wsgi:app
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: restaurant-db
          property: connectionString
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: EMAIL_PASSWORD
        sync: false

databases:
  - name: restaurant-db
    databaseName: restaurant
    user: restaurant_user