services:
  - type: web
    name: restaurant-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_SECRET_KEY
        value: your-secret-value
      - key: DATABASE_URL
        value: sqlite:///restaurant.db
