"""added quantity to cartFood

Revision ID: 2423cffb00e6
Revises: 76b9334c807e
Create Date: 2025-03-20 13:00:04.309202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2423cffb00e6'
down_revision = '76b9334c807e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_foods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_foods', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
