"""added special_instructions to Cart

Revision ID: 59443e0e97d9
Revises: 7f4b4bb726f8
Create Date: 2025-04-04 14:50:18.701256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59443e0e97d9'
down_revision = '7f4b4bb726f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('special_instructions', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_column('special_instructions')

    # ### end Alembic commands ###
