"""Removed payment_status from Cart

Revision ID: 76b9334c807e
Revises: ad8556aaa998
Create Date: 2025-03-20 12:08:40.406796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76b9334c807e'
down_revision = 'ad8556aaa998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_column('payment_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
