"""remove special_instructions from CartFood

Revision ID: 7f4b4bb726f8
Revises: d2cd6adeb2a1
Create Date: 2025-04-04 14:46:29.289873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f4b4bb726f8'
down_revision = 'd2cd6adeb2a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_foods', schema=None) as batch_op:
        batch_op.drop_column('special_instructions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_foods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('special_instructions', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
